#!/bin/bash

#
# Create Dropbox directories
#

echo " - creating Dropbox directories..."
mkdir -p /dbox/Dropbox
ln /dbox/Dropbox /files
echo " - done."

#
# Download and Extract Dropbox Headless
#

echo " - downloading and extracting Dropbox headless..."
cd /dbox
wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
echo " - done."

#
# Download and install Dropbox CLI
#

echo " - downloading and extracting Dropbox CLI..."
wget https://www.dropbox.com/download?dl=packages/dropbox.py -O /usr/local/bin/dropbox-cli
chmod +x /usr/local/bin/dropbox-cli
echo " - done."
