#!/usr/bin/with-contenv bash

#======================================================================================================================
# Create Dropbox user and group
# Originally from https://github.com/axllent/alpine-dropbox/blob/master/init.sh
#
# Modifications copyright (c) 2020 Ben Green <https://bcgdesign.com>
#======================================================================================================================

echo " - creating Dropbox user and group..."

if [[ ! $(getent group $GID) ]]; then
    addgroup --gid $GID dbox
fi

if [[ ! $(getent passwd $UID) ]]; then
    adduser --system --disabled-password --no-create-home --home /dbox --shell /bin/bash --uid $UID --gid $GID dbox
else
    USERNAME=$(awk -v val=$UID -F ":" '$3==val{print $1}' /etc/passwd)
    usermod -l dbox $USERNAME
    usermod -g $GID dbox
fi

usermod -aG sudo dbox

echo " - done."
