#!/usr/bin/with-contenv bash

#======================================================================================================================
# Create Dropbox user and group
# Originally from https://github.com/axllent/alpine-dropbox/blob/master/init.sh
#
# Modifications copyright (c) 2020 Ben Green <https://bcgdesign.com>
#======================================================================================================================

DBOX="dbox"

#
# Add group if it doesn't exist
#

if [[ ! $(getent group $GID) ]]; then

    echo " - creating group dbox..."
    addgroup --gid $GID $DBOX
    echo " - done."

fi


#
# Add user if it doesn't exist
#

if [[ ! $(getent passwd $UID) ]] ; then

    echo " - creating user $DBOX..."
    adduser --system --disabled-password --no-create-home --home /dbox --shell /bin/bash --uid $UID --gid $GID $DBOX
    usermod -aG sudo $DBOX
    echo " - done."

#
# Modify user if it does exist
#

else
    
    USERNAME=$(awk -v val=$UID -F ":" '$3==val{print $1}' /etc/passwd)

    if [[ ! "$USERNAME" == $DBOX ]] ; then

        echo " - modifying user $UID..." && \
        usermod \
            -d /dbox \
            -g $GID \
            -l $DBOX \
            -s /bin/bash \
            -aG sudo \
            $USERNAME
        echo " - done."

    else

        echo " - user $DBOX already exists."

    fi

fi
