#!/bin/bash

echo " - setting executable permissions..."
chmod +x /usr/bin/healthcheck
echo " - done."

echo " - setting permissions on Dropbox folder..."
chown -R $UID:$GID /dbox/Dropbox
chmod -R g+rwx /dbox/Dropbox
echo " - done."
