#!/bin/bash

echo " - running Dropbox status..."

#======================================================================================================================
# From https://github.com/axllent/alpine-dropbox/blob/master/dropbox-status.sh
#======================================================================================================================

STORED=""
while true ; do
    if [ -f '/dbox/.dropbox-dist/VERSION' ]; then
        CUR="$(runuser -u dbox -c "dropbox-cli status")";
        if [ "$STORED" != "$CUR" ]; then
            STORED="$CUR"
            echo "$STORED"
        fi
    fi
    sleep 1
done
