#!/bin/bash

echo " - Dropbox status..."

#======================================================================================================================
# From https://github.com/axllent/alpine-dropbox/blob/master/dropbox-status.sh
#======================================================================================================================

STORED=""
while true ; do
    if [ -f '/dbox/.dropbox-dist/VERSION' ]; then
        CUR="$(runuser dbox -c "~/cli status")";
        if [ "$STORED" != "$CUR" ]; then
            STORED="$CUR"
            echo " - status: $STORED"
        fi
    fi
    sleep 1
done
